repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: .zarray
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: name-tests-test
        args: [--pytest-test-first]
    -   id: check-docstring-first
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
    -   id: ruff
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        pass_filenames: false  # needed if excluding files with pyproject.toml or setup.cfg
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        additional_dependencies:
        - tomli
